# Generated by Django 4.2.11 on 2024-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='desc',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(blank=True, default='Anonymous author', max_length=100, null=True),
        ),
    ]
