# Generated by Django 4.2.11 on 2024-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_desc_blogmodel_content_remove_blogmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='poster',
            field=models.ImageField(default=1, upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
