# Generated by Django 4.2.11 on 2024-03-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogmodel_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.profilemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='poster',
            field=models.ImageField(upload_to='blog_image'),
        ),
    ]
